FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS `DATABASE_NAME_PLACEHOLDER`;

FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'USER_NAME_PLACEHOLDER'@'%' IDENTIFIED BY 'USER_PASSWORD_PLACEHOLDER';

GRANT ALL ON `DATABASE_NAME_PLACEHOLDER`.* TO 'USER_NAME_PLACEHOLDER'@'%';

FLUSH PRIVILEGES;

ALTER USER 'root'@'%' IDENTIFIED BY 'ROOT_PASSWORD_PLACEHOLDER';

FLUSH PRIVILEGES;

-- # mysql -h 127.0.0.1 -P 3306 -u testuser -p --database=wordpress_data
-- # mysql -h 127.0.0.1 -P 3306 -u root -p
-- # testpw
-- # \s - status
-- # \g - send command
-- # SHOW DATABASES;
-- # use wordpress_data
-- # SHOW GRANTS FOR CURRENT_USER;